backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
slug:
  clean_accents: true

media_library:
  config:
    multiple: false
public_folder: "/uploads"

collections:
  - name: "articles"
    label: "Artículos"
    folder: "content/articles"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Fecha", name: "date", widget: "datetime"}
      - {label: "Resumen (Excerpt)", name: "excerpt", widget: "text"}
      - {label: "Autor", name: "author", widget: "string", default: "Dame Marcha"}
      - {label: "Sección", name: "section", widget: "select", options: ["musica", "cine"]}
      - {label: "Categoría", name: "categoryLabel", widget: "string"}
      - {label: "Imagen de Portada", name: "image", widget: "image"}
      - {label: "Contenido del Artículo", name: "body", widget: "markdown"}
